### PR TITLE
add php 8 support

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by gianarb** [comment]
Hey @samsonasik ! Thank you for your help here. I am not really into PHP for a couple of years anymore.
If it sounds valuable to you do you want to be added to this repository as a maintainer?

Can you add PHP 8 to travis.yaml as well?
Thanks

**Comment by samsonasik** [comment]
Hi @gianarb you can add me as maintainer ;). Yes, I will add php 8 to travis.yaml when I've a chance

**Comment by samsonasik** [comment]
also, could you migrate travis.org to travis.com ? Thank you.

**Comment by gianarb** [comment]
I have migrated the project

**Comment by samsonasik** [comment]
updated requirement to `^7.3 || ~8.0` for 1.0.0 release.

**Comment by samsonasik** [comment]
released https://github.com/gianarb/angry/releases/tag/1.0.0 for it :tada:

**Comment by samsonasik** [comment]
@gianarb in packagist seems not auto-updated for version 1.0.0, could you click force update in packagist https://packagist.org/packages/gianarb/angry ? 

Thank you.

**Comment by samsonasik** [comment]
oh, I can manually click update myself ;), just can't set auto-update

**Pull request merged**
